#!/bin/sh

ln -s ~/dotfiles/git/gitconfig ~/.gitconfig
ln -s ~/dotfiles/git/gitignore_global ~/.gitignore_global
ln -s ~/dotfiles/zsh ~/.zsh
ln -s ~/dotfiles/Renviron ~/.Renviron
ln -s ~/dotfiles/Rprofile ~/.Rprofile
ln -s ~/dotfiles/Xdefaults ~/.Xdefaults
ln -s ~/dotfiles/bash_alias ~/.bash_alias
ln -s ~/dotfiles/bash_prompt ~/.bash_prompt
ln -s ~/dotfiles/bashrc ~/.bashrc
ln -s ~/dotfiles/gnuplot ~/.gnuplot
ln -s ~/dotfiles/inputrc ~/.inputrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/zshrc ~/.zshrc
